name: tests

on:
  push:
  workflow_dispatch:

jobs:
  build-openrag-from-scratch:
    runs-on: ubuntu-latest
    steps:
      - name: Update apt and install packages
        run: |
          sudo apt update
          sudo apt install -y curl git jq

      -
        name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: v2.34.0

      -
        name: Checkout current branch
        uses: actions/checkout@v5
        with:
          submodules: true

      -
        name: Set up mini env
        run: cp .github/workflows/mini/.env ./ && cp .github/workflows/mini/*.yaml ./

      -
        name: Build
        run: docker compose --profile cpu build

      -
        name: Run
        run: docker compose --profile cpu up -d && .github/workflows/mini/wait_for_healthy.sh openrag-vllm-cpu-1


      -
        name: List containers
        run: docker container ls

      -
        name: Detect openrag-cpu ip address
        run: ADDR=`docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' openrag-openrag-cpu-1` && echo ${ADDR} && echo "addr end"

      -
        name: Print openrag-cpu ip address
        run: echo "openrag-cpu IP is "${ADDR}"end"

      -
        name: Sleep 60s
        run: sleep 60s

      -
        name: Install Python venv
        run: python3 -m venv venv && source venv/bin/activate && pip3 install -r utility/requirements.txt

      -
        name: Index 500 documents
        run: .github/workflows/mini/index_docs.sh

      -
        name: Prnt
        run: ls -lah && sleep 20s && docker container ls

