name: tests

on:
  push:
  workflow_dispatch:

jobs:
  build-openrag-from-scratch:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: v2.34.0

      -
        name: Checkout current branch
        uses: actions/checkout@v5
        with:
          submodules: true

      -
        name: Set up mini env
        run: cp .github/workflows/mini/.env ./ && cp .github/workflows/mini/*.yaml ./

      -
        name: Build
        run: docker compose --profile cpu build

      -
        name: Run
        run: docker compose --profile cpu up -d && .github/workflows/mini/wait_for_healthy.sh openrag-openrag-cpu-1

      -
        name: Prnt
        run: ls -lah && sleep 20s && docker container ls

